# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      WALLET_ZIP: ${{ secrets.WALLET_ZIP }}
      ENV_FILE: ${{ secrets.ENV_FILE }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install dependencies
        run: make install-deps

      - name: setup wallet and environment
        run: |
          echo "${ENV_FILE}" . ~/dev.env
          echo "${WALLET_ZIP}" > ~/wallet.zip
          . ~/dev/env
          unzip ~/wallet.zip -d ./${WALLET_PATH}/

      - name: test
        run: |
          make test
          
      - name: rollback
        if: failure()
        run: |
          echo Roll back schema changes
          echo Re-deploy latest app version
